<a href="https://colab.research.google.com/github/lucassuryana/intro_python_spatial_analytics/blob/main/Python_for_Spatial_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Table Conversion and Cleansing**

In [ ]:
# Lakukan instalasi library ArcGIS, setelah run pertama kali, klik "RESTART RUNTIME" lalu run kembali
!pip install arcgis

Collecting arcgis
  Downloading https://files.pythonhosted.org/packages/a3/42/f612a2b678893e018ac521d9e131ae589230c9209d5b50dd19496f921a18/arcgis-1.8.5.post3.tar.gz (3.2MB)
     |████████████████████████████████| 3.2MB 3.7MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from arcgis) (1.15.0)
Requirement already satisfied: ipywidgets>=7 in /usr/local/lib/python3.7/dist-packages (from arcgis) (7.6.3)
Requirement already satisfied: widgetsnbextension>=3 in /usr/local/lib/python3.7/dist-packages (from arcgis) (3.5.1)
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.7/dist-packages (from arcgis) (1.1.5)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from arcgis) (1.19.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from arcgis) (3.2.2)
Collecting keyring>=19
  Using cached https://files.pythonhosted.org/packages/26/f9/41230ac47f738f1ba66676dc8d3b30ca5b1f9eb0230fc204bcd9836c4ae9/keyring-23.0.1-py3-none-any.whl
Collecting lerc
  Using cached https://files.pythonhosted.org/packages/f2/20/73c8fa29a4ba8f8cbdb037369e6b61ac9253664a8aa0912b52169192447f/lerc-0.1.0.tar.gz
Collecting ujson>=3
  Using cached https://files.pythonhosted.org/packages/17/4e/50e8e4cf5f00b537095711c2c86ac4d7191aed2b4fffd5a19f06898f6929/ujson-4.0.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting jupyterlab
  Using cached https://files.pythonhosted.org/packages/72/e7/20a304e3b2137387f131d0f10031554700aec8206d633e3fb1b231d72843/jupyterlab-3.0.15-py3-none-any.whl
Collecting python-certifi-win32
  Using cached https://files.pythonhosted.org/packages/c1/43/916ef701ae481e04ed87af26fd54fa3906d44239f32d7f43be2fcbf54896/python_certifi_win32-1.6-py2.py3-none-any.whl
Collecting pyshp>=2
  Using cached https://files.pythonhosted.org/packages/38/85/fbf87e7aa55103e0d06af756bdbc15cf821fa580414c23142d60a35d4f85/pyshp-2.1.3.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from arcgis) (2.23.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.7/dist-packages (from arcgis) (1.3.0)
Collecting requests_toolbelt
  Using cached https://files.pythonhosted.org/packages/60/ef/7681134338fc097acef8d9b2f8abe0458e4d87559c689a8c306d0957ece5/requests_toolbelt-0.9.1-py2.py3-none-any.whl
Collecting requests_ntlm
  Using cached https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7->arcgis) (4.10.1)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7->arcgis) (5.0.5)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7->arcgis) (5.5.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7->arcgis) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7->arcgis) (1.0.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension>=3->arcgis) (5.3.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1->arcgis) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1->arcgis) (2018.9)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->arcgis) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->arcgis) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->arcgis) (1.3.1)
Collecting SecretStorage>=3.2; sys_platform == "linux"
  Using cached https://files.pythonhosted.org/packages/d9/1e/29cd69fdac7391aa51510dfd42aa70b4e6a826c8cd019ee2a8ab9ec0777f/SecretStorage-3.3.1-py3-none-any.whl
Collecting jeepney>=0.4.2; sys_platform == "linux"
  Using cached https://files.pythonhosted.org/packages/51/b0/a6ea72741aaac3f37fb96d195e4ee576a103c4c04e279bc6b446a70960e1/jeepney-0.6.0-py3-none-any.whl
Requirement already satisfied: importlib-metadata>=3.6 in /usr/local/lib/python3.7/dist-packages (from keyring>=19->arcgis) (4.0.1)
Collecting jupyter-server~=1.4
  Using cached https://files.pythonhosted.org/packages/97/ca/d6f503c2f594f43d0d467f7ec34337541eb847a03c1f605e1be6cc4196d9/jupyter_server-1.7.0-py3-none-any.whl
Collecting nbclassic~=0.2
  Using cached https://files.pythonhosted.org/packages/c7/ec/a56d6775abaab99c224a977dc907ff458986edaad8116ab75b6081867131/nbclassic-0.2.8-py3-none-any.whl
Collecting tornado>=6.1.0
  Using cached https://files.pythonhosted.org/packages/91/a8/9c5902233fa3c2e6a889cbd164333ddda5009669f494e3fadbeee2c03af5/tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl
Requirement already satisfied: jinja2>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyterlab->arcgis) (2.11.3)
Collecting jupyterlab-server~=2.3
  Using cached https://files.pythonhosted.org/packages/2b/8a/eb527b9eda76a70a7343dd42bbc492d1824410f9310b0a798598963db5c9/jupyterlab_server-2.5.1-py3-none-any.whl
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from jupyterlab->arcgis) (4.7.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from jupyterlab->arcgis) (20.9)
Collecting setuptools-scm
  Using cached https://files.pythonhosted.org/packages/c4/d5/e50358c82026f44cd8810c8165002746cd3f8b78865f6bcf5d7f0fe4f652/setuptools_scm-6.0.1-py3-none-any.whl
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from python-certifi-win32->arcgis) (2020.12.5)
Requirement already satisfied: wrapt>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from python-certifi-win32->arcgis) (1.12.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->arcgis) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->arcgis) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->arcgis) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib->arcgis) (3.1.0)
Collecting cryptography>=1.3
  Using cached https://files.pythonhosted.org/packages/b2/26/7af637e6a7e87258b963f1731c5982fb31cd507f0d90d91836e446955d02/cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl
Collecting ntlm-auth>=1.0.2
  Using cached https://files.pythonhosted.org/packages/ff/84/97c550164b54942b0e908c31ef09d9469f3ba4cd7332a671e2125732f63b/ntlm_auth-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7->arcgis) (5.3.5)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets>=4.3.1->ipywidgets>=7->arcgis) (0.2.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (56.1.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (0.8.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (2.6.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (4.8.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7->arcgis) (2.6.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension>=3->arcgis) (5.6.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension>=3->arcgis) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.9.5)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=3.6->keyring>=19->arcgis) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=3.6->keyring>=19->arcgis) (3.4.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.7/dist-packages (from jupyter-server~=1.4->jupyterlab->arcgis) (0.10.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.7/dist-packages (from jupyter-server~=1.4->jupyterlab->arcgis) (20.1.0)
Collecting websocket-client
  Using cached https://files.pythonhosted.org/packages/f7/0c/d52a2a63512a613817846d430d16a8fbe5ea56dd889e89c68facf6b91cb6/websocket_client-0.59.0-py2.py3-none-any.whl
Collecting anyio<4,>=3.0.1; python_version >= "3.7"
  Using cached https://files.pythonhosted.org/packages/23/75/8d31e0de8c87cb17aecde237def16383569737ae9e15d99ac54eafc61f78/anyio-3.0.1-py3-none-any.whl
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.7/dist-packages (from jupyter-server~=1.4->jupyterlab->arcgis) (22.0.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2>=2.1->jupyterlab->arcgis) (2.0.0)
Collecting json5
  Using cached https://files.pythonhosted.org/packages/2b/81/22bf51a5bc60dde18bb6164fd597f18ee683de8670e141364d9c432dd3cf/json5-0.9.5-py2.py3-none-any.whl
Requirement already satisfied: babel in /usr/local/lib/python3.7/dist-packages (from jupyterlab-server~=2.3->jupyterlab->arcgis) (2.9.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=1.3->requests_ntlm->arcgis) (1.14.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7->arcgis) (0.7.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (3.3.0)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.3)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.4.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (1.4.3)
Collecting sniffio>=1.1
  Using cached https://files.pythonhosted.org/packages/52/b0/7b2e028b63d092804b6794595871f936aafa5e9322dcaaad50ebf67445b3/sniffio-1.2.0-py3-none-any.whl
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=1.3->requests_ntlm->arcgis) (2.20)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension>=3->arcgis) (0.5.1)
Building wheels for collected packages: arcgis, lerc, pyshp
  Building wheel for arcgis (setup.py) ... done
  Created wheel for arcgis: filename=arcgis-1.8.5.post3-py2.py3-none-any.whl size=3598424 sha256=b90c575a5a1371d775180b84aa25026e22240bdada7d7a0d8a7f2a4c155e2ea6
  Stored in directory: /root/.cache/pip/wheels/89/8a/95/9adcde37c32f4c90dc00e5e89d935bbf0ea56df79cb2b97bbb
  Building wheel for lerc (setup.py) ... done
  Created wheel for lerc: filename=lerc-0.1.0-cp37-none-any.whl size=571698 sha256=ea48a2d0e7ed1548a96167efca09680a26a1efe9fa8d1a29ea6a8f63697b8e46
  Stored in directory: /root/.cache/pip/wheels/91/25/fc/0975ce9d050d66a246aa3cd51b04af4ef94a8ad96ccda87f86
  Building wheel for pyshp (setup.py) ... done
  Created wheel for pyshp: filename=pyshp-2.1.3-cp37-none-any.whl size=37264 sha256=27be539fa9c1807dc4816d9cc73832dfc0bb756bb615851bc6c0a984523edb07
  Stored in directory: /root/.cache/pip/wheels/76/2b/d4/53e6b9a0fb0a9f9f29664cf82605af8bc81d5ab44d987896dd
Successfully built arcgis lerc pyshp
ERROR: google-colab 1.0.0 has requirement tornado~=5.1.0; python_version >= "3.0", but you'll have tornado 6.1 which is incompatible.
ERROR: jupyter-server 1.7.0 has requirement jupyter-client>=6.1.1, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: jupyterlab-server 2.5.1 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
Installing collected packages: cryptography, jeepney, SecretStorage, keyring, lerc, ujson, websocket-client, tornado, sniffio, anyio, jupyter-server, nbclassic, json5, jupyterlab-server, jupyterlab, setuptools-scm, python-certifi-win32, pyshp, requests-toolbelt, ntlm-auth, requests-ntlm, arcgis
  Found existing installation: tornado 5.1.1
    Uninstalling tornado-5.1.1:
      Successfully uninstalled tornado-5.1.1
Successfully installed SecretStorage-3.3.1 anyio-3.0.1 arcgis-1.8.5.post3 cryptography-3.4.7 jeepney-0.6.0 json5-0.9.5 jupyter-server-1.7.0 jupyterlab-3.0.15 jupyterlab-server-2.5.1 keyring-23.0.1 lerc-0.1.0 nbclassic-0.2.8 ntlm-auth-1.5.0 pyshp-2.1.3 python-certifi-win32-1.6 requests-ntlm-1.1.0 requests-toolbelt-0.9.1 setuptools-scm-6.0.1 sniffio-1.2.0 tornado-6.1 ujson-4.0.2 websocket-client-0.59.0

In [ ]:
# Lakukan instalasi geopython libraries
!apt install gdal-bin python-gdal python3-gdal 
# Instal rtree (Geopandas requirement)
!apt install python3-rtree 
# Instal Geopandas
!pip install git+git://github.com/geopandas/geopandas.git
# Instal descartes (Geopandas requirment)
!pip install descartes

Reading package lists... Done
Building dependency tree
Reading state information... Done
gdal-bin is already the newest version (2.2.3+dfsg-2).
python-gdal is already the newest version (2.2.3+dfsg-2).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  python3-numpy
Suggested packages:
  python-numpy-doc python3-nose python3-numpy-dbg
The following NEW packages will be installed:
  python3-gdal python3-numpy
0 upgraded, 2 newly installed, 0 to remove and 34 not upgraded.
Need to get 2,288 kB of archives.
After this operation, 13.2 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-numpy amd64 1:1.13.3-2ubuntu1 [1,943 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-gdal amd64 2.2.3+dfsg-2 [346 kB]
Fetched 2,288 kB in 2s (964 kB/s)
Selecting previously unselected package python3-numpy.
(Reading database ... 160706 files and directories currently installed.)
Preparing to unpack .../python3-numpy_1%3a1.13.3-2ubuntu1_amd64.deb ...
Unpacking python3-numpy (1:1.13.3-2ubuntu1) ...
Selecting previously unselected package python3-gdal.
Preparing to unpack .../python3-gdal_2.2.3+dfsg-2_amd64.deb ...
Unpacking python3-gdal (2.2.3+dfsg-2) ...
Setting up python3-numpy (1:1.13.3-2ubuntu1) ...
Setting up python3-gdal (2.2.3+dfsg-2) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libspatialindex-c4v5 libspatialindex-dev libspatialindex4v5
  python3-pkg-resources
Suggested packages:
  python3-setuptools
The following NEW packages will be installed:
  libspatialindex-c4v5 libspatialindex-dev libspatialindex4v5
  python3-pkg-resources python3-rtree
0 upgraded, 5 newly installed, 0 to remove and 34 not upgraded.
Need to get 671 kB of archives.
After this operation, 3,948 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libspatialindex4v5 amd64 1.8.5-5 [219 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libspatialindex-c4v5 amd64 1.8.5-5 [51.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-pkg-resources all 39.0.1-2 [98.8 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libspatialindex-dev amd64 1.8.5-5 [285 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python3-rtree all 0.8.3+ds-1 [16.9 kB]
Fetched 671 kB in 2s (325 kB/s)
Selecting previously unselected package libspatialindex4v5:amd64.
(Reading database ... 161116 files and directories currently installed.)
Preparing to unpack .../libspatialindex4v5_1.8.5-5_amd64.deb ...
Unpacking libspatialindex4v5:amd64 (1.8.5-5) ...
Selecting previously unselected package libspatialindex-c4v5:amd64.
Preparing to unpack .../libspatialindex-c4v5_1.8.5-5_amd64.deb ...
Unpacking libspatialindex-c4v5:amd64 (1.8.5-5) ...
Selecting previously unselected package python3-pkg-resources.
Preparing to unpack .../python3-pkg-resources_39.0.1-2_all.deb ...
Unpacking python3-pkg-resources (39.0.1-2) ...
Selecting previously unselected package libspatialindex-dev:amd64.
Preparing to unpack .../libspatialindex-dev_1.8.5-5_amd64.deb ...
Unpacking libspatialindex-dev:amd64 (1.8.5-5) ...
Selecting previously unselected package python3-rtree.
Preparing to unpack .../python3-rtree_0.8.3+ds-1_all.deb ...
Unpacking python3-rtree (0.8.3+ds-1) ...
Setting up libspatialindex4v5:amd64 (1.8.5-5) ...
Setting up python3-pkg-resources (39.0.1-2) ...
Setting up libspatialindex-c4v5:amd64 (1.8.5-5) ...
Setting up libspatialindex-dev:amd64 (1.8.5-5) ...
Setting up python3-rtree (0.8.3+ds-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

Collecting git+git://github.com/geopandas/geopandas.git
  Cloning git://github.com/geopandas/geopandas.git to /tmp/pip-req-build-zkvimos1
  Running command git clone -q git://github.com/geopandas/geopandas.git /tmp/pip-req-build-zkvimos1
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas==0.9.0+24.ga26bde2) (1.1.5)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas==0.9.0+24.ga26bde2) (1.7.1)
Collecting fiona>=1.8
  Downloading https://files.pythonhosted.org/packages/ea/2a/404b22883298a3efe9c6ef8d67acbf2c38443fa366ee9cd4cd34e17626ea/Fiona-1.8.19-cp37-cp37m-manylinux1_x86_64.whl (15.3MB)
     |████████████████████████████████| 15.3MB 279kB/s
Collecting pyproj>=2.2.0
  Downloading https://files.pythonhosted.org/packages/b1/72/d52e9ca81caef056062d71991b0e9b1d16af042245627c5d0e4916a36c4f/pyproj-3.0.1-cp37-cp37m-manylinux2010_x86_64.whl (6.5MB)
     |████████████████████████████████| 6.5MB 35.8MB/s
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas==0.9.0+24.ga26bde2) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas==0.9.0+24.ga26bde2) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas==0.9.0+24.ga26bde2) (2018.9)
Collecting click<8,>=4.0
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
     |████████████████████████████████| 92kB 10.7MB/s
Collecting click-plugins>=1.0
  Downloading https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
Collecting cligj>=0.5
  Downloading https://files.pythonhosted.org/packages/42/1e/947eadf10d6804bf276eb8a038bd5307996dceaaa41cfd21b7a15ec62f5d/cligj-0.7.1-py3-none-any.whl
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.9.0+24.ga26bde2) (2020.12.5)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.9.0+24.ga26bde2) (1.15.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.9.0+24.ga26bde2) (21.2.0)
Collecting munch
  Downloading https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
Building wheels for collected packages: geopandas
  Building wheel for geopandas (setup.py) ... done
  Created wheel for geopandas: filename=geopandas-0.9.0+24.ga26bde2-py2.py3-none-any.whl size=995296 sha256=1fcd7fcc35f283925c103ac2609f64b8c92194fd933738d29e9bf5e6c6666d4f
  Stored in directory: /tmp/pip-ephem-wheel-cache-6amouvyl/wheels/91/24/71/376c9c67192694168352afcccc2d264248f7e2cc6192997186
Successfully built geopandas
Installing collected packages: click, click-plugins, cligj, munch, fiona, pyproj, geopandas
  Found existing installation: click 8.0.0
    Uninstalling click-8.0.0:
      Successfully uninstalled click-8.0.0
Successfully installed click-7.1.2 click-plugins-1.1.1 cligj-0.7.1 fiona-1.8.19 geopandas-0.9.0+24.ga26bde2 munch-2.5.0 pyproj-3.0.1
Requirement already satisfied: descartes in /usr/local/lib/python3.7/dist-packages (1.1.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from descartes) (3.2.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->descartes) (2.4.7)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib->descartes) (1.19.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->descartes) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->descartes) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->descartes) (2.8.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from cycler>=0.10->matplotlib->descartes) (1.15.0)

In [ ]:
# Lakukan instalasi library Geopandas
%pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.7/dist-packages (0.9.0+24.ga26bde2)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.19)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.1.5)
Requirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.7.1)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (3.0.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2020.12.5)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2.5.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.2.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.1.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)
Requirement already satisfied: click<8,>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (0.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->geopandas) (2018.9)

In [ ]:
# Lakukan instalasi Tabula (untuk konversi data pdf)
!pip install tabula-py

Collecting tabula-py
  Downloading https://files.pythonhosted.org/packages/cf/29/d6cb0d77ef46d84d35cffa09cf42c73b373aea664d28604eab6818f8a47c/tabula_py-2.2.0-py3-none-any.whl (11.7MB)
     |████████████████████████████████| 11.7MB 4.1MB/s
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.1.5)
Collecting distro
  Downloading https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Installing collected packages: distro, tabula-py
Successfully installed distro-1.5.0 tabula-py-2.2.0

In [ ]:
# Upload file pdf (Laporan_Nasional_RKD2018_FINAL.pdf) dari folder local computer, klik "Choose Files"
%cd /content/
from google.colab import files
files.upload()

/content

{}

In [ ]:
# Akses data pdf tersebut pada direktori Google Colab
from tabula import read_pdf
df = read_pdf('Laporan_Nasional_RKD2018_FINAL.pdf', pages = 64)

Got stderr: May 15, 2021 5:29:52 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
May 15, 2021 5:29:52 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
May 15, 2021 5:29:52 AM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 17 fonts

In [ ]:
# Tampilkan data pdf dalam bentuk tabel (dataframe)
df[0]

             Unnamed: 0 Unnamed: 1  ...    Unnamed: 5  Unnamed: 6
0                   NaN   Provinsi  ...  Sangat Sulit           N
1                   NaN        NaN  ...        95% CI  tertimbang
2                  Aceh        NaN  ...     26.3 30.5       4,876
3        Sumatera Utara        NaN  ...     23.0 26.1      12,528
4        Sumatera Barat        NaN  ...     24.7 29.0       4,601
5                  Riau        NaN  ...     32.9 38.0       5,901
6                 Jambi        NaN  ...     39.1 44.8       3,377
7      Sumatera Selatan        NaN  ...     39.6 44.5       7,550
8              Bengkulu        NaN  ...     25.3 30.8       1,909
9               Lampung        NaN  ...     32.8 37.9       7,530
10      Bangka Belitung        NaN  ...     19.8 26.1       1,408
11       Kepulauan Riau        NaN  ...     12.4 18.6       2,148
12          DKI Jakarta        NaN  ...     14.3 18.2      11,203
13           Jawa Barat        NaN  ...     28.3 30.8      49,558
14          Jawa Tengah        NaN  ...     16.8 18.8      35,293
15        DI Yogyakarta        NaN  ...       6.2 9.3       4,258
16            JawaTimur        NaN  ...     15.8 17.5      39,773
17               Banten        NaN  ...     21.7 25.9      11,021
18                 Bali        NaN  ...      8.7 11.9       4,205
19  Nusa Tenggara Barat        NaN  ...     24.0 29.0       5,041
20  Nusa Tenggara Timur        NaN  ...     52.4 56.8       4,149
21           Kalimantan      Barat  ...     43.4 48.5       3,995
22           Kalimantan     Tengah  ...     44.6 50.8       2,479
23           Kalimantan    Selatan  ...     18.9 23.1       4,182
24           Kalimantan      Timur  ...     25.7 31.5       3,424
25           Kalimantan      Utara  ...     23.8 31.2         617
26       Sulawesi Utara        NaN  ...     26.7 32.0       2,362
27      Sulawesi Tengah        NaN  ...     38.8 44.7       2,550
28     Sulawesi Selatan        NaN  ...     25.4 28.7       7,919
29    Sulawesi Tenggara        NaN  ...     32.2 38.7       2,039
30            Gorontalo        NaN  ...     28.9 36.9       1,065
31       Sulawesi Barat        NaN  ...     45.7 55.5       1,119
32               Maluku        NaN  ...     40.7 48.7       1,330
33         Maluku Utara        NaN  ...     38.0 46.3         899
34          Papua Barat        NaN  ...     34.8 44.5         845
35                Papua        NaN  ...     56.6 61.9       2,933
36            INDONESIA        NaN  ...     25.6 26.4     254,087

[37 rows x 8 columns]

In [ ]:
# Panggil library yang dibutuhkan
import numpy as np
# Hilangkan yang NaN dengan nilai kosong
df_edit = df[0].replace(np.nan, '')
df_edit

             Unnamed: 0 Unnamed: 1  ...    Unnamed: 5  Unnamed: 6
0                         Provinsi  ...  Sangat Sulit           N
1                                   ...        95% CI  tertimbang
2                  Aceh             ...     26.3 30.5       4,876
3        Sumatera Utara             ...     23.0 26.1      12,528
4        Sumatera Barat             ...     24.7 29.0       4,601
5                  Riau             ...     32.9 38.0       5,901
6                 Jambi             ...     39.1 44.8       3,377
7      Sumatera Selatan             ...     39.6 44.5       7,550
8              Bengkulu             ...     25.3 30.8       1,909
9               Lampung             ...     32.8 37.9       7,530
10      Bangka Belitung             ...     19.8 26.1       1,408
11       Kepulauan Riau             ...     12.4 18.6       2,148
12          DKI Jakarta             ...     14.3 18.2      11,203
13           Jawa Barat             ...     28.3 30.8      49,558
14          Jawa Tengah             ...     16.8 18.8      35,293
15        DI Yogyakarta             ...       6.2 9.3       4,258
16            JawaTimur             ...     15.8 17.5      39,773
17               Banten             ...     21.7 25.9      11,021
18                 Bali             ...      8.7 11.9       4,205
19  Nusa Tenggara Barat             ...     24.0 29.0       5,041
20  Nusa Tenggara Timur             ...     52.4 56.8       4,149
21           Kalimantan      Barat  ...     43.4 48.5       3,995
22           Kalimantan     Tengah  ...     44.6 50.8       2,479
23           Kalimantan    Selatan  ...     18.9 23.1       4,182
24           Kalimantan      Timur  ...     25.7 31.5       3,424
25           Kalimantan      Utara  ...     23.8 31.2         617
26       Sulawesi Utara             ...     26.7 32.0       2,362
27      Sulawesi Tengah             ...     38.8 44.7       2,550
28     Sulawesi Selatan             ...     25.4 28.7       7,919
29    Sulawesi Tenggara             ...     32.2 38.7       2,039
30            Gorontalo             ...     28.9 36.9       1,065
31       Sulawesi Barat             ...     45.7 55.5       1,119
32               Maluku             ...     40.7 48.7       1,330
33         Maluku Utara             ...     38.0 46.3         899
34          Papua Barat             ...     34.8 44.5         845
35                Papua             ...     56.6 61.9       2,933
36            INDONESIA             ...     25.6 26.4     254,087

[37 rows x 8 columns]

In [ ]:
# Gabungkan kolom pertama dengan kolom kedua
df_edit.iloc[:,0] = df_edit.iloc[:,0] + ' ' + df_edit.iloc[:,1]
df_edit

              Unnamed: 0 Unnamed: 1  ...    Unnamed: 5  Unnamed: 6
0               Provinsi   Provinsi  ...  Sangat Sulit           N
1                                    ...        95% CI  tertimbang
2                  Aceh              ...     26.3 30.5       4,876
3        Sumatera Utara              ...     23.0 26.1      12,528
4        Sumatera Barat              ...     24.7 29.0       4,601
5                  Riau              ...     32.9 38.0       5,901
6                 Jambi              ...     39.1 44.8       3,377
7      Sumatera Selatan              ...     39.6 44.5       7,550
8              Bengkulu              ...     25.3 30.8       1,909
9               Lampung              ...     32.8 37.9       7,530
10      Bangka Belitung              ...     19.8 26.1       1,408
11       Kepulauan Riau              ...     12.4 18.6       2,148
12          DKI Jakarta              ...     14.3 18.2      11,203
13           Jawa Barat              ...     28.3 30.8      49,558
14          Jawa Tengah              ...     16.8 18.8      35,293
15        DI Yogyakarta              ...       6.2 9.3       4,258
16            JawaTimur              ...     15.8 17.5      39,773
17               Banten              ...     21.7 25.9      11,021
18                 Bali              ...      8.7 11.9       4,205
19  Nusa Tenggara Barat              ...     24.0 29.0       5,041
20  Nusa Tenggara Timur              ...     52.4 56.8       4,149
21      Kalimantan Barat      Barat  ...     43.4 48.5       3,995
22     Kalimantan Tengah     Tengah  ...     44.6 50.8       2,479
23    Kalimantan Selatan    Selatan  ...     18.9 23.1       4,182
24      Kalimantan Timur      Timur  ...     25.7 31.5       3,424
25      Kalimantan Utara      Utara  ...     23.8 31.2         617
26       Sulawesi Utara              ...     26.7 32.0       2,362
27      Sulawesi Tengah              ...     38.8 44.7       2,550
28     Sulawesi Selatan              ...     25.4 28.7       7,919
29    Sulawesi Tenggara              ...     32.2 38.7       2,039
30            Gorontalo              ...     28.9 36.9       1,065
31       Sulawesi Barat              ...     45.7 55.5       1,119
32               Maluku              ...     40.7 48.7       1,330
33         Maluku Utara              ...     38.0 46.3         899
34          Papua Barat              ...     34.8 44.5         845
35                Papua              ...     56.6 61.9       2,933
36            INDONESIA              ...     25.6 26.4     254,087

[37 rows x 8 columns]

In [ ]:
# Hapus dua baris pertama dan baris paling akhir
df_edit = df_edit.iloc[2:-1].reset_index(drop=True)
df_edit

              Unnamed: 0 Unnamed: 1 Unnamed: 2  ... Unnamed: 4 Unnamed: 5 Unnamed: 6
0                  Aceh                   29.8  ...       28.4  26.3 30.5      4,876
1        Sumatera Utara                   38.8  ...       24.5  23.0 26.1     12,528
2        Sumatera Barat                   35.1  ...       26.8  24.7 29.0      4,601
3                  Riau                   36.6  ...       35.4  32.9 38.0      5,901
4                 Jambi                   25.3  ...       41.9  39.1 44.8      3,377
5      Sumatera Selatan                   24.9  ...       42.0  39.6 44.5      7,550
6              Bengkulu                   33.3  ...       28.0  25.3 30.8      1,909
7               Lampung                   26.6  ...       35.3  32.8 37.9      7,530
8       Bangka Belitung                   46.5  ...       22.8  19.8 26.1      1,408
9        Kepulauan Riau                   59.3  ...       15.2  12.4 18.6      2,148
10          DKI Jakarta                   52.3  ...       16.2  14.3 18.2     11,203
11           Jawa Barat                   32.3  ...       29.5  28.3 30.8     49,558
12          Jawa Tengah                   40.9  ...       17.8  16.8 18.8     35,293
13        DI Yogyakarta                   70.6  ...        7.6    6.2 9.3      4,258
14            JawaTimur                   41.3  ...       16.6  15.8 17.5     39,773
15               Banten                   38.4  ...       23.7  21.7 25.9     11,021
16                 Bali                   60.5  ...       10.2   8.7 11.9      4,205
17  Nusa Tenggara Barat                   27.3  ...       26.4  24.0 29.0      5,041
18  Nusa Tenggara Timur                   24.5  ...       54.6  52.4 56.8      4,149
19      Kalimantan Barat      Barat       28.4  ...       45.9  43.4 48.5      3,995
20     Kalimantan Tengah     Tengah       28.3  ...       47.7  44.6 50.8      2,479
21    Kalimantan Selatan    Selatan       39.3  ...       20.9  18.9 23.1      4,182
22      Kalimantan Timur      Timur       43.9  ...       28.5  25.7 31.5      3,424
23      Kalimantan Utara      Utara       39.1  ...       27.4  23.8 31.2        617
24       Sulawesi Utara                   35.8  ...       29.3  26.7 32.0      2,362
25      Sulawesi Tengah                   30.3  ...       41.7  38.8 44.7      2,550
26     Sulawesi Selatan                   29.8  ...       27.0  25.4 28.7      7,919
27    Sulawesi Tenggara                   27.9  ...       35.4  32.2 38.7      2,039
28            Gorontalo                   33.1  ...       32.8  28.9 36.9      1,065
29       Sulawesi Barat                   21.0  ...       50.6  45.7 55.5      1,119
30               Maluku                   26.8  ...       44.7  40.7 48.7      1,330
31         Maluku Utara                   31.4  ...       42.1  38.0 46.3        899
32          Papua Barat                   34.5  ...       39.6  34.8 44.5        845
33                Papua                   19.3  ...       59.3  56.6 61.9      2,933

[34 rows x 8 columns]

In [ ]:
# Hilangkan kolom kedua
df_edit = df_edit.iloc[:,[0,2,3,4,5,6,7]]
df_edit

              Unnamed: 0 Unnamed: 2 Unnamed: 3  ... Unnamed: 4 Unnamed: 5 Unnamed: 6
0                  Aceh        29.8  27.9 31.7  ...       28.4  26.3 30.5      4,876
1        Sumatera Utara        38.8  37.1 40.4  ...       24.5  23.0 26.1     12,528
2        Sumatera Barat        35.1  32.9 37.4  ...       26.8  24.7 29.0      4,601
3                  Riau        36.6  34.3 38.9  ...       35.4  32.9 38.0      5,901
4                 Jambi        25.3  22.9 27.9  ...       41.9  39.1 44.8      3,377
5      Sumatera Selatan        24.9  23.0 27.0  ...       42.0  39.6 44.5      7,550
6              Bengkulu        33.3  30.8 35.9  ...       28.0  25.3 30.8      1,909
7               Lampung        26.6  24.3 29.1  ...       35.3  32.8 37.9      7,530
8       Bangka Belitung        46.5  43.3 49.7  ...       22.8  19.8 26.1      1,408
9        Kepulauan Riau        59.3  54.7 63.7  ...       15.2  12.4 18.6      2,148
10          DKI Jakarta        52.3  49.9 54.7  ...       16.2  14.3 18.2     11,203
11           Jawa Barat        32.3  31.0 33.6  ...       29.5  28.3 30.8     49,558
12          Jawa Tengah        40.9  39.8 42.1  ...       17.8  16.8 18.8     35,293
13        DI Yogyakarta        70.6  68.0 73.2  ...        7.6    6.2 9.3      4,258
14            JawaTimur        41.3  40.2 42.5  ...       16.6  15.8 17.5     39,773
15               Banten        38.4  35.9 40.9  ...       23.7  21.7 25.9     11,021
16                 Bali        60.5  57.8 63.1  ...       10.2   8.7 11.9      4,205
17  Nusa Tenggara Barat        27.3  24.9 29.7  ...       26.4  24.0 29.0      5,041
18  Nusa Tenggara Timur        24.5  22.7 26.3  ...       54.6  52.4 56.8      4,149
19      Kalimantan Barat       28.4  26.1 31.0  ...       45.9  43.4 48.5      3,995
20     Kalimantan Tengah       28.3  25.6 31.1  ...       47.7  44.6 50.8      2,479
21    Kalimantan Selatan       39.3  36.9 41.8  ...       20.9  18.9 23.1      4,182
22      Kalimantan Timur       43.9  40.6 47.2  ...       28.5  25.7 31.5      3,424
23      Kalimantan Utara       39.1  34.0 44.4  ...       27.4  23.8 31.2        617
24       Sulawesi Utara        35.8  33.3 38.4  ...       29.3  26.7 32.0      2,362
25      Sulawesi Tengah        30.3  27.9 32.9  ...       41.7  38.8 44.7      2,550
26     Sulawesi Selatan        29.8  28.2 31.5  ...       27.0  25.4 28.7      7,919
27    Sulawesi Tenggara        27.9  25.3 30.6  ...       35.4  32.2 38.7      2,039
28            Gorontalo        33.1  29.8 36.7  ...       32.8  28.9 36.9      1,065
29       Sulawesi Barat        21.0  17.3 25.3  ...       50.6  45.7 55.5      1,119
30               Maluku        26.8  23.2 30.7  ...       44.7  40.7 48.7      1,330
31         Maluku Utara        31.4  28.3 34.7  ...       42.1  38.0 46.3        899
32          Papua Barat        34.5  30.3 39.0  ...       39.6  34.8 44.5        845
33                Papua        19.3  17.4 21.3  ...       59.3  56.6 61.9      2,933

[34 rows x 7 columns]

In [ ]:
# Di bagian kanan data, tambahkan kolom yang diperlukan dan split kolom yang menyatu
df_edit['Mudah'] = df_edit.iloc[:,1]
df_edit[['Sulit', 'Sulit1', 'Sulit2']] = df_edit.iloc[:,3].str.split(' ',expand=True)
df_edit['Sangat_Sulit'] = df_edit.iloc[:,4]
df_edit

              Unnamed: 0 Unnamed: 2 Unnamed: 3  ... Sulit1 Sulit2 Sangat_Sulit
0                  Aceh        29.8  27.9 31.7  ...   39.6   44.1         28.4
1        Sumatera Utara        38.8  37.1 40.4  ...   35.0   38.5         24.5
2        Sumatera Barat        35.1  32.9 37.4  ...   35.8   40.4         26.8
3                  Riau        36.6  34.3 38.9  ...   25.6   30.5         35.4
4                 Jambi        25.3  22.9 27.9  ...   29.8   35.8         41.9
5      Sumatera Selatan        24.9  23.0 27.0  ...   30.4   35.7         42.0
6              Bengkulu        33.3  30.8 35.9  ...   35.9   41.7         28.0
7               Lampung        26.6  24.3 29.1  ...   35.6   40.7         35.3
8       Bangka Belitung        46.5  43.3 49.7  ...   27.4   34.3         22.8
9        Kepulauan Riau        59.3  54.7 63.7  ...   21.4   30.1         15.2
10          DKI Jakarta        52.3  49.9 54.7  ...   29.4   33.8         16.2
11           Jawa Barat        32.3  31.0 33.6  ...   36.9   39.5         29.5
12          Jawa Tengah        40.9  39.8 42.1  ...   40.1   42.5         17.8
13        DI Yogyakarta        70.6  68.0 73.2  ...   19.7   24.0          7.6
14            JawaTimur        41.3  40.2 42.5  ...   40.9   43.2         16.6
15               Banten        38.4  35.9 40.9  ...   35.5   40.4         23.7
16                 Bali        60.5  57.8 63.1  ...   27.0   31.8         10.2
17  Nusa Tenggara Barat        27.3  24.9 29.7  ...   43.5   49.2         26.4
18  Nusa Tenggara Timur        24.5  22.7 26.3  ...   19.1   22.8         54.6
19      Kalimantan Barat       28.4  26.1 31.0  ...   23.0   28.4         45.9
20     Kalimantan Tengah       28.3  25.6 31.1  ...   21.1   27.3         47.7
21    Kalimantan Selatan       39.3  36.9 41.8  ...   37.2   42.4         20.9
22      Kalimantan Timur       43.9  40.6 47.2  ...   24.6   30.8         28.5
23      Kalimantan Utara       39.1  34.0 44.4  ...   28.4   39.1         27.4
24       Sulawesi Utara        35.8  33.3 38.4  ...   32.3   37.6         29.3
25      Sulawesi Tengah        30.3  27.9 32.9  ...   25.3   30.8         41.7
26     Sulawesi Selatan        29.8  28.2 31.5  ...   41.3   45.1         27.0
27    Sulawesi Tenggara        27.9  25.3 30.6  ...   33.7   40.0         35.4
28            Gorontalo        33.1  29.8 36.7  ...   30.1   38.4         32.8
29       Sulawesi Barat        21.0  17.3 25.3  ...   24.1   33.0         50.6
30               Maluku        26.8  23.2 30.7  ...   24.9   32.5         44.7
31         Maluku Utara        31.4  28.3 34.7  ...   23.1   30.2         42.1
32          Papua Barat        34.5  30.3 39.0  ...   22.2   30.0         39.6
33                Papua        19.3  17.4 21.3  ...   19.2   23.9         59.3

[34 rows x 12 columns]

In [ ]:
# Ambil kolom yang diperlukan
df_edit = df_edit.iloc[:,[0,7,8,11]]
df_edit

              Unnamed: 0 Mudah Sulit Sangat_Sulit
0                  Aceh   29.8  41.8         28.4
1        Sumatera Utara   38.8  36.7         24.5
2        Sumatera Barat   35.1  38.1         26.8
3                  Riau   36.6  28.0         35.4
4                 Jambi   25.3  32.7         41.9
5      Sumatera Selatan   24.9  33.0         42.0
6              Bengkulu   33.3  38.7         28.0
7               Lampung   26.6  38.1         35.3
8       Bangka Belitung   46.5  30.7         22.8
9        Kepulauan Riau   59.3  25.5         15.2
10          DKI Jakarta   52.3  31.5         16.2
11           Jawa Barat   32.3  38.2         29.5
12          Jawa Tengah   40.9  41.3         17.8
13        DI Yogyakarta   70.6  21.8          7.6
14            JawaTimur   41.3  42.0         16.6
15               Banten   38.4  37.9         23.7
16                 Bali   60.5  29.3         10.2
17  Nusa Tenggara Barat   27.3  46.3         26.4
18  Nusa Tenggara Timur   24.5  20.9         54.6
19      Kalimantan Barat  28.4  25.6         45.9
20     Kalimantan Tengah  28.3  24.1         47.7
21    Kalimantan Selatan  39.3  39.8         20.9
22      Kalimantan Timur  43.9  27.6         28.5
23      Kalimantan Utara  39.1  33.6         27.4
24       Sulawesi Utara   35.8  34.9         29.3
25      Sulawesi Tengah   30.3  28.0         41.7
26     Sulawesi Selatan   29.8  43.2         27.0
27    Sulawesi Tenggara   27.9  36.8         35.4
28            Gorontalo   33.1  34.1         32.8
29       Sulawesi Barat   21.0  28.4         50.6
30               Maluku   26.8  28.6         44.7
31         Maluku Utara   31.4  26.5         42.1
32          Papua Barat   34.5  25.9         39.6
33                Papua   19.3  21.5         59.3

In [ ]:
# Lakukan penamaan kolom pertama
df_edit = df_edit.rename(columns={
               df_edit.columns[0]:'Provinsi',
                        }
              )
df_edit

                Provinsi Mudah Sulit Sangat_Sulit
0                  Aceh   29.8  41.8         28.4
1        Sumatera Utara   38.8  36.7         24.5
2        Sumatera Barat   35.1  38.1         26.8
3                  Riau   36.6  28.0         35.4
4                 Jambi   25.3  32.7         41.9
5      Sumatera Selatan   24.9  33.0         42.0
6              Bengkulu   33.3  38.7         28.0
7               Lampung   26.6  38.1         35.3
8       Bangka Belitung   46.5  30.7         22.8
9        Kepulauan Riau   59.3  25.5         15.2
10          DKI Jakarta   52.3  31.5         16.2
11           Jawa Barat   32.3  38.2         29.5
12          Jawa Tengah   40.9  41.3         17.8
13        DI Yogyakarta   70.6  21.8          7.6
14            JawaTimur   41.3  42.0         16.6
15               Banten   38.4  37.9         23.7
16                 Bali   60.5  29.3         10.2
17  Nusa Tenggara Barat   27.3  46.3         26.4
18  Nusa Tenggara Timur   24.5  20.9         54.6
19      Kalimantan Barat  28.4  25.6         45.9
20     Kalimantan Tengah  28.3  24.1         47.7
21    Kalimantan Selatan  39.3  39.8         20.9
22      Kalimantan Timur  43.9  27.6         28.5
23      Kalimantan Utara  39.1  33.6         27.4
24       Sulawesi Utara   35.8  34.9         29.3
25      Sulawesi Tengah   30.3  28.0         41.7
26     Sulawesi Selatan   29.8  43.2         27.0
27    Sulawesi Tenggara   27.9  36.8         35.4
28            Gorontalo   33.1  34.1         32.8
29       Sulawesi Barat   21.0  28.4         50.6
30               Maluku   26.8  28.6         44.7
31         Maluku Utara   31.4  26.5         42.1
32          Papua Barat   34.5  25.9         39.6
33                Papua   19.3  21.5         59.3

In [ ]:
# Sesuaikan nama provinsi agar dapat dijoin dengan data spasial (shapefile) 
# dengan merubah teks "JawaTimur" menjadi "Jawa Timur"
df_edit = df_edit.replace(to_replace='JawaTimur',value='Jawa Timur', regex=True)
df_edit

                Provinsi Mudah Sulit Sangat_Sulit
0                  Aceh   29.8  41.8         28.4
1        Sumatera Utara   38.8  36.7         24.5
2        Sumatera Barat   35.1  38.1         26.8
3                  Riau   36.6  28.0         35.4
4                 Jambi   25.3  32.7         41.9
5      Sumatera Selatan   24.9  33.0         42.0
6              Bengkulu   33.3  38.7         28.0
7               Lampung   26.6  38.1         35.3
8       Bangka Belitung   46.5  30.7         22.8
9        Kepulauan Riau   59.3  25.5         15.2
10          DKI Jakarta   52.3  31.5         16.2
11           Jawa Barat   32.3  38.2         29.5
12          Jawa Tengah   40.9  41.3         17.8
13        DI Yogyakarta   70.6  21.8          7.6
14           Jawa Timur   41.3  42.0         16.6
15               Banten   38.4  37.9         23.7
16                 Bali   60.5  29.3         10.2
17  Nusa Tenggara Barat   27.3  46.3         26.4
18  Nusa Tenggara Timur   24.5  20.9         54.6
19      Kalimantan Barat  28.4  25.6         45.9
20     Kalimantan Tengah  28.3  24.1         47.7
21    Kalimantan Selatan  39.3  39.8         20.9
22      Kalimantan Timur  43.9  27.6         28.5
23      Kalimantan Utara  39.1  33.6         27.4
24       Sulawesi Utara   35.8  34.9         29.3
25      Sulawesi Tengah   30.3  28.0         41.7
26     Sulawesi Selatan   29.8  43.2         27.0
27    Sulawesi Tenggara   27.9  36.8         35.4
28            Gorontalo   33.1  34.1         32.8
29       Sulawesi Barat   21.0  28.4         50.6
30               Maluku   26.8  28.6         44.7
31         Maluku Utara   31.4  26.5         42.1
32          Papua Barat   34.5  25.9         39.6
33                Papua   19.3  21.5         59.3

In [ ]:
# Export data ke csv, output akan terlihat pada direktori folder Google Colab (sebelah kiri), tunggu beberapa saat
df_edit.to_csv('Riskesdas_Python.csv')

**2. Join Table with Spatial Data**

In [ ]:
# Panggil library
import geopandas as gpd

In [ ]:
# Panggil data csv sebagai dataframe
sdf = gpd.read_file('Riskesdas_Python.csv')
sdf

   field_1              Provinsi Mudah Sulit Sangat_Sulit geometry
0        0                 Aceh   29.8  41.8         28.4     None
1        1       Sumatera Utara   38.8  36.7         24.5     None
2        2       Sumatera Barat   35.1  38.1         26.8     None
3        3                 Riau   36.6  28.0         35.4     None
4        4                Jambi   25.3  32.7         41.9     None
5        5     Sumatera Selatan   24.9  33.0         42.0     None
6        6             Bengkulu   33.3  38.7         28.0     None
7        7              Lampung   26.6  38.1         35.3     None
8        8      Bangka Belitung   46.5  30.7         22.8     None
9        9       Kepulauan Riau   59.3  25.5         15.2     None
10      10          DKI Jakarta   52.3  31.5         16.2     None
11      11           Jawa Barat   32.3  38.2         29.5     None
12      12          Jawa Tengah   40.9  41.3         17.8     None
13      13        DI Yogyakarta   70.6  21.8          7.6     None
14      14           Jawa Timur   41.3  42.0         16.6     None
15      15               Banten   38.4  37.9         23.7     None
16      16                 Bali   60.5  29.3         10.2     None
17      17  Nusa Tenggara Barat   27.3  46.3         26.4     None
18      18  Nusa Tenggara Timur   24.5  20.9         54.6     None
19      19      Kalimantan Barat  28.4  25.6         45.9     None
20      20     Kalimantan Tengah  28.3  24.1         47.7     None
21      21    Kalimantan Selatan  39.3  39.8         20.9     None
22      22      Kalimantan Timur  43.9  27.6         28.5     None
23      23      Kalimantan Utara  39.1  33.6         27.4     None
24      24       Sulawesi Utara   35.8  34.9         29.3     None
25      25      Sulawesi Tengah   30.3  28.0         41.7     None
26      26     Sulawesi Selatan   29.8  43.2         27.0     None
27      27    Sulawesi Tenggara   27.9  36.8         35.4     None
28      28            Gorontalo   33.1  34.1         32.8     None
29      29       Sulawesi Barat   21.0  28.4         50.6     None
30      30               Maluku   26.8  28.6         44.7     None
31      31         Maluku Utara   31.4  26.5         42.1     None
32      32          Papua Barat   34.5  25.9         39.6     None
33      33                Papua   19.3  21.5         59.3     None

In [ ]:
# Lakukan penamaan kolom pertama
sdf = sdf.rename(columns={
               sdf.columns[0]:'KODE',
                        }
              )
sdf

   KODE              Provinsi Mudah Sulit Sangat_Sulit geometry
0     0                 Aceh   29.8  41.8         28.4     None
1     1       Sumatera Utara   38.8  36.7         24.5     None
2     2       Sumatera Barat   35.1  38.1         26.8     None
3     3                 Riau   36.6  28.0         35.4     None
4     4                Jambi   25.3  32.7         41.9     None
5     5     Sumatera Selatan   24.9  33.0         42.0     None
6     6             Bengkulu   33.3  38.7         28.0     None
7     7              Lampung   26.6  38.1         35.3     None
8     8      Bangka Belitung   46.5  30.7         22.8     None
9     9       Kepulauan Riau   59.3  25.5         15.2     None
10   10          DKI Jakarta   52.3  31.5         16.2     None
11   11           Jawa Barat   32.3  38.2         29.5     None
12   12          Jawa Tengah   40.9  41.3         17.8     None
13   13        DI Yogyakarta   70.6  21.8          7.6     None
14   14           Jawa Timur   41.3  42.0         16.6     None
15   15               Banten   38.4  37.9         23.7     None
16   16                 Bali   60.5  29.3         10.2     None
17   17  Nusa Tenggara Barat   27.3  46.3         26.4     None
18   18  Nusa Tenggara Timur   24.5  20.9         54.6     None
19   19      Kalimantan Barat  28.4  25.6         45.9     None
20   20     Kalimantan Tengah  28.3  24.1         47.7     None
21   21    Kalimantan Selatan  39.3  39.8         20.9     None
22   22      Kalimantan Timur  43.9  27.6         28.5     None
23   23      Kalimantan Utara  39.1  33.6         27.4     None
24   24       Sulawesi Utara   35.8  34.9         29.3     None
25   25      Sulawesi Tengah   30.3  28.0         41.7     None
26   26     Sulawesi Selatan   29.8  43.2         27.0     None
27   27    Sulawesi Tenggara   27.9  36.8         35.4     None
28   28            Gorontalo   33.1  34.1         32.8     None
29   29       Sulawesi Barat   21.0  28.4         50.6     None
30   30               Maluku   26.8  28.6         44.7     None
31   31         Maluku Utara   31.4  26.5         42.1     None
32   32          Papua Barat   34.5  25.9         39.6     None
33   33                Papua   19.3  21.5         59.3     None

In [ ]:
# Ambil kolom yang diperlukan
sdf = sdf.iloc[:,[0,1,2,3,4]]
sdf

   KODE              Provinsi Mudah Sulit Sangat_Sulit
0     0                 Aceh   29.8  41.8         28.4
1     1       Sumatera Utara   38.8  36.7         24.5
2     2       Sumatera Barat   35.1  38.1         26.8
3     3                 Riau   36.6  28.0         35.4
4     4                Jambi   25.3  32.7         41.9
5     5     Sumatera Selatan   24.9  33.0         42.0
6     6             Bengkulu   33.3  38.7         28.0
7     7              Lampung   26.6  38.1         35.3
8     8      Bangka Belitung   46.5  30.7         22.8
9     9       Kepulauan Riau   59.3  25.5         15.2
10   10          DKI Jakarta   52.3  31.5         16.2
11   11           Jawa Barat   32.3  38.2         29.5
12   12          Jawa Tengah   40.9  41.3         17.8
13   13        DI Yogyakarta   70.6  21.8          7.6
14   14           Jawa Timur   41.3  42.0         16.6
15   15               Banten   38.4  37.9         23.7
16   16                 Bali   60.5  29.3         10.2
17   17  Nusa Tenggara Barat   27.3  46.3         26.4
18   18  Nusa Tenggara Timur   24.5  20.9         54.6
19   19      Kalimantan Barat  28.4  25.6         45.9
20   20     Kalimantan Tengah  28.3  24.1         47.7
21   21    Kalimantan Selatan  39.3  39.8         20.9
22   22      Kalimantan Timur  43.9  27.6         28.5
23   23      Kalimantan Utara  39.1  33.6         27.4
24   24       Sulawesi Utara   35.8  34.9         29.3
25   25      Sulawesi Tengah   30.3  28.0         41.7
26   26     Sulawesi Selatan   29.8  43.2         27.0
27   27    Sulawesi Tenggara   27.9  36.8         35.4
28   28            Gorontalo   33.1  34.1         32.8
29   29       Sulawesi Barat   21.0  28.4         50.6
30   30               Maluku   26.8  28.6         44.7
31   31         Maluku Utara   31.4  26.5         42.1
32   32          Papua Barat   34.5  25.9         39.6
33   33                Papua   19.3  21.5         59.3

In [ ]:
# Ubah tipe data pada kolom-kolom data csv agar dapat dilakukan join dengan data spasial (shapefile)
sdf['KODE']=sdf['KODE'].astype(int)
sdf['Mudah']=sdf['Mudah'].astype(float)
sdf['Sulit']=sdf['Sulit'].astype(float)
sdf['Sangat_Sulit']=sdf['Sangat_Sulit'].astype(float)

/usr/local/lib/python3.7/dist-packages/geopandas/geodataframe.py:1325: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)

In [ ]:
# Upload semua data 'Provinsi' dalam folder Provinsi (data spasial 'Provinsi.shp' dan ekstensi yang berbeda-beda)
# Klik "Choose Files" dan tunggu beberapa saat sampai semua data 'Provinsi' terupload
%cd /content/
from google.colab import files
files.upload()

/content

Saving Provinsi.CPG to Provinsi.CPG
Saving Provinsi.dbf to Provinsi.dbf
Saving Provinsi.prj to Provinsi.prj
Saving Provinsi.sbn to Provinsi.sbn
Saving Provinsi.sbx to Provinsi.sbx
Saving Provinsi.shp to Provinsi.shp
Saving Provinsi.shp.xml to Provinsi.shp.xml
Saving Provinsi.shx to Provinsi.shx

In [ ]:
# Akses data spasial (shapefile) batas provinsi yang sudah diupload
spatial_data = gpd.read_file('Provinsi.shp')
spatial_data

    KODE  ...                                           geometry
0      8  ...  MULTIPOLYGON (((107.96173 -3.41100, 107.96220 ...
1     28  ...  MULTIPOLYGON (((122.81573 0.84676, 122.81579 0...
2      3  ...  MULTIPOLYGON (((101.64432 -0.82552, 101.64344 ...
3     10  ...  MULTIPOLYGON (((106.73563 -6.04014, 106.73548 ...
4      9  ...  MULTIPOLYGON (((105.25355 -1.29511, 105.25032 ...
5     26  ...  MULTIPOLYGON (((117.20354 -7.75841, 117.20369 ...
6      5  ...  MULTIPOLYGON (((106.16177 -3.29708, 106.16225 ...
7     19  ...  MULTIPOLYGON (((110.20428 -3.06763, 110.20409 ...
8      0  ...  MULTIPOLYGON (((96.66509 2.12018, 96.66765 2.1...
9      6  ...  MULTIPOLYGON (((102.37586 -5.36968, 102.38067 ...
10     7  ...  MULTIPOLYGON (((105.44636 -6.13334, 105.44676 ...
11    12  ...  MULTIPOLYGON (((108.78495 -7.70727, 108.78469 ...
12    17  ...  MULTIPOLYGON (((117.05418 -9.10635, 117.05385 ...
13     1  ...  MULTIPOLYGON (((98.51677 -0.45696, 98.51546 -0...
14     4  ...  MULTIPOLYGON (((104.40900 -0.85951, 104.40870 ...
15    15  ...  MULTIPOLYGON (((105.54977 -6.99566, 105.55035 ...
16    14  ...  MULTIPOLYGON (((114.20384 -8.65725, 114.20366 ...
17    13  ...  MULTIPOLYGON (((110.57922 -8.13975, 110.57915 ...
18    21  ...  MULTIPOLYGON (((115.67458 -4.72922, 115.67484 ...
19    24  ...  MULTIPOLYGON (((124.31403 0.40777, 124.31389 0...
20    23  ...  MULTIPOLYGON (((117.11810 2.74988, 117.11823 2...
21    29  ...  MULTIPOLYGON (((119.35876 -3.48674, 119.35869 ...
22    31  ...  MULTIPOLYGON (((124.44807 -2.04010, 124.44798 ...
23    20  ...  MULTIPOLYGON (((115.29113 -2.22390, 115.28742 ...
24    18  ...  MULTIPOLYGON (((122.87141 -10.96885, 122.87312...
25    32  ...  MULTIPOLYGON (((133.36781 -4.10860, 133.37085 ...
26    11  ...  MULTIPOLYGON (((108.36713 -6.27222, 108.36694 ...
27    27  ...  MULTIPOLYGON (((122.73676 -6.21321, 122.73655 ...
28     2  ...  MULTIPOLYGON (((100.56964 -3.27509, 100.56933 ...
29    33  ...  MULTIPOLYGON (((138.83786 -8.09071, 138.83705 ...
30    22  ...  MULTIPOLYGON (((116.46150 -2.19154, 116.42979 ...
31    30  ...  MULTIPOLYGON (((130.92404 -8.25113, 130.92422 ...
32    16  ...  MULTIPOLYGON (((114.61025 -8.12284, 114.61015 ...
33    25  ...  MULTIPOLYGON (((123.17950 -3.59840, 123.18001 ...

[34 rows x 5 columns]

In [ ]:
# Lakukan join table dari csv (dataframe) ke dalam data spasial dengan atribut "KODE" sebagai primary key
spatial_data = spatial_data.merge(sdf, on='KODE')
spatial_data

    KODE  Shape_Leng  Shape_Area  ... Mudah Sulit Sangat_Sulit
0      8   19.496815    1.362708  ...  46.5  30.7         22.8
1     28   10.836366    0.978359  ...  33.1  34.1         32.8
2      3   34.467502    7.302953  ...  36.6  28.0         35.4
3     10    3.111914    0.053398  ...  52.3  31.5         16.2
4      9   65.097163    0.672994  ...  59.3  25.5         15.2
5     26   30.099549    3.702836  ...  29.8  43.2         27.0
6      5   20.775366    7.078590  ...  24.9  33.0         42.0
7     19   38.116377   11.934140  ...  28.4  25.6         45.9
8      0   26.908954    4.630154  ...  29.8  41.8         28.4
9      6   11.203636    1.612857  ...  33.3  38.7         28.0
10     7   15.212649    2.730434  ...  26.6  38.1         35.3
11    12   15.458152    2.819734  ...  40.9  41.3         17.8
12    17   27.033356    1.615771  ...  27.3  46.3         26.4
13     1   29.413189    5.872789  ...  38.8  36.7         24.5
14     4   12.020288    3.979657  ...  25.3  32.7         41.9
15    15    8.901867    0.764512  ...  38.4  37.9         23.7
16    14   32.934628    3.934116  ...  41.3  42.0         16.6
17    13    3.323107    0.260496  ...  70.6  21.8          7.6
18    21   26.605910    3.040403  ...  39.3  39.8         20.9
19    24   22.011358    1.179057  ...  35.8  34.9         29.3
20    23   51.120969    5.704864  ...  39.1  33.6         27.4
21    29   10.610070    1.347556  ...  21.0  28.4         50.6
22    31   59.693529    2.560542  ...  31.4  26.5         42.1
23    20   23.001035   12.494212  ...  28.3  24.1         47.7
24    18   52.220495    3.821908  ...  24.5  20.9         54.6
25    32   75.106730    8.010370  ...  34.5  25.9         39.6
26    11   11.762909    3.032266  ...  32.3  38.2         29.5
27    27   38.673734    2.983705  ...  27.9  36.8         35.4
28     2   27.726194    3.424717  ...  35.1  38.1         26.8
29    33   63.784356   25.587117  ...  19.3  21.5         59.3
30    22   56.747412   10.226469  ...  43.9  27.6         28.5
31    30   85.404699    3.779791  ...  26.8  28.6         44.7
32    16    5.666217    0.458949  ...  60.5  29.3         10.2
33    25   60.140261    4.969973  ...  30.3  28.0         41.7

[34 rows x 9 columns]

In [ ]:
# Ambil kolom yang dibutuhkan
spatial_data = spatial_data.iloc[:,[0,1,2,3,4,6,7,8]]
spatial_data

    KODE  Shape_Leng  Shape_Area  ... Mudah Sulit  Sangat_Sulit
0      8   19.496815    1.362708  ...  46.5  30.7          22.8
1     28   10.836366    0.978359  ...  33.1  34.1          32.8
2      3   34.467502    7.302953  ...  36.6  28.0          35.4
3     10    3.111914    0.053398  ...  52.3  31.5          16.2
4      9   65.097163    0.672994  ...  59.3  25.5          15.2
5     26   30.099549    3.702836  ...  29.8  43.2          27.0
6      5   20.775366    7.078590  ...  24.9  33.0          42.0
7     19   38.116377   11.934140  ...  28.4  25.6          45.9
8      0   26.908954    4.630154  ...  29.8  41.8          28.4
9      6   11.203636    1.612857  ...  33.3  38.7          28.0
10     7   15.212649    2.730434  ...  26.6  38.1          35.3
11    12   15.458152    2.819734  ...  40.9  41.3          17.8
12    17   27.033356    1.615771  ...  27.3  46.3          26.4
13     1   29.413189    5.872789  ...  38.8  36.7          24.5
14     4   12.020288    3.979657  ...  25.3  32.7          41.9
15    15    8.901867    0.764512  ...  38.4  37.9          23.7
16    14   32.934628    3.934116  ...  41.3  42.0          16.6
17    13    3.323107    0.260496  ...  70.6  21.8           7.6
18    21   26.605910    3.040403  ...  39.3  39.8          20.9
19    24   22.011358    1.179057  ...  35.8  34.9          29.3
20    23   51.120969    5.704864  ...  39.1  33.6          27.4
21    29   10.610070    1.347556  ...  21.0  28.4          50.6
22    31   59.693529    2.560542  ...  31.4  26.5          42.1
23    20   23.001035   12.494212  ...  28.3  24.1          47.7
24    18   52.220495    3.821908  ...  24.5  20.9          54.6
25    32   75.106730    8.010370  ...  34.5  25.9          39.6
26    11   11.762909    3.032266  ...  32.3  38.2          29.5
27    27   38.673734    2.983705  ...  27.9  36.8          35.4
28     2   27.726194    3.424717  ...  35.1  38.1          26.8
29    33   63.784356   25.587117  ...  19.3  21.5          59.3
30    22   56.747412   10.226469  ...  43.9  27.6          28.5
31    30   85.404699    3.779791  ...  26.8  28.6          44.7
32    16    5.666217    0.458949  ...  60.5  29.3          10.2
33    25   60.140261    4.969973  ...  30.3  28.0          41.7

[34 rows x 8 columns]

In [ ]:
# Perbaiki penamaan kolom Provinsi
spatial_data = spatial_data.rename(columns={
               spatial_data.columns[3]:'Provinsi',
                        }
              )
spatial_data

    KODE  Shape_Leng  Shape_Area  ... Mudah Sulit  Sangat_Sulit
0      8   19.496815    1.362708  ...  46.5  30.7          22.8
1     28   10.836366    0.978359  ...  33.1  34.1          32.8
2      3   34.467502    7.302953  ...  36.6  28.0          35.4
3     10    3.111914    0.053398  ...  52.3  31.5          16.2
4      9   65.097163    0.672994  ...  59.3  25.5          15.2
5     26   30.099549    3.702836  ...  29.8  43.2          27.0
6      5   20.775366    7.078590  ...  24.9  33.0          42.0
7     19   38.116377   11.934140  ...  28.4  25.6          45.9
8      0   26.908954    4.630154  ...  29.8  41.8          28.4
9      6   11.203636    1.612857  ...  33.3  38.7          28.0
10     7   15.212649    2.730434  ...  26.6  38.1          35.3
11    12   15.458152    2.819734  ...  40.9  41.3          17.8
12    17   27.033356    1.615771  ...  27.3  46.3          26.4
13     1   29.413189    5.872789  ...  38.8  36.7          24.5
14     4   12.020288    3.979657  ...  25.3  32.7          41.9
15    15    8.901867    0.764512  ...  38.4  37.9          23.7
16    14   32.934628    3.934116  ...  41.3  42.0          16.6
17    13    3.323107    0.260496  ...  70.6  21.8           7.6
18    21   26.605910    3.040403  ...  39.3  39.8          20.9
19    24   22.011358    1.179057  ...  35.8  34.9          29.3
20    23   51.120969    5.704864  ...  39.1  33.6          27.4
21    29   10.610070    1.347556  ...  21.0  28.4          50.6
22    31   59.693529    2.560542  ...  31.4  26.5          42.1
23    20   23.001035   12.494212  ...  28.3  24.1          47.7
24    18   52.220495    3.821908  ...  24.5  20.9          54.6
25    32   75.106730    8.010370  ...  34.5  25.9          39.6
26    11   11.762909    3.032266  ...  32.3  38.2          29.5
27    27   38.673734    2.983705  ...  27.9  36.8          35.4
28     2   27.726194    3.424717  ...  35.1  38.1          26.8
29    33   63.784356   25.587117  ...  19.3  21.5          59.3
30    22   56.747412   10.226469  ...  43.9  27.6          28.5
31    30   85.404699    3.779791  ...  26.8  28.6          44.7
32    16    5.666217    0.458949  ...  60.5  29.3          10.2
33    25   60.140261    4.969973  ...  30.3  28.0          41.7

[34 rows x 8 columns]

In [ ]:
# Export hasil join table ke shapefile (shp)
# Tunggu beberapa saat sampai hasil export 'Riskesdas_Provinsi' muncul di direktori sebelah kiri
spatial_data.to_file('Riskesdas_Provinsi.shp')
spatial_data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.

    KODE  Shape_Leng  Shape_Area  ... Mudah Sulit  Sangat_Sulit
0      8   19.496815    1.362708  ...  46.5  30.7          22.8
1     28   10.836366    0.978359  ...  33.1  34.1          32.8
2      3   34.467502    7.302953  ...  36.6  28.0          35.4
3     10    3.111914    0.053398  ...  52.3  31.5          16.2
4      9   65.097163    0.672994  ...  59.3  25.5          15.2
5     26   30.099549    3.702836  ...  29.8  43.2          27.0
6      5   20.775366    7.078590  ...  24.9  33.0          42.0
7     19   38.116377   11.934140  ...  28.4  25.6          45.9
8      0   26.908954    4.630154  ...  29.8  41.8          28.4
9      6   11.203636    1.612857  ...  33.3  38.7          28.0
10     7   15.212649    2.730434  ...  26.6  38.1          35.3
11    12   15.458152    2.819734  ...  40.9  41.3          17.8
12    17   27.033356    1.615771  ...  27.3  46.3          26.4
13     1   29.413189    5.872789  ...  38.8  36.7          24.5
14     4   12.020288    3.979657  ...  25.3  32.7          41.9
15    15    8.901867    0.764512  ...  38.4  37.9          23.7
16    14   32.934628    3.934116  ...  41.3  42.0          16.6
17    13    3.323107    0.260496  ...  70.6  21.8           7.6
18    21   26.605910    3.040403  ...  39.3  39.8          20.9
19    24   22.011358    1.179057  ...  35.8  34.9          29.3
20    23   51.120969    5.704864  ...  39.1  33.6          27.4
21    29   10.610070    1.347556  ...  21.0  28.4          50.6
22    31   59.693529    2.560542  ...  31.4  26.5          42.1
23    20   23.001035   12.494212  ...  28.3  24.1          47.7
24    18   52.220495    3.821908  ...  24.5  20.9          54.6
25    32   75.106730    8.010370  ...  34.5  25.9          39.6
26    11   11.762909    3.032266  ...  32.3  38.2          29.5
27    27   38.673734    2.983705  ...  27.9  36.8          35.4
28     2   27.726194    3.424717  ...  35.1  38.1          26.8
29    33   63.784356   25.587117  ...  19.3  21.5          59.3
30    22   56.747412   10.226469  ...  43.9  27.6          28.5
31    30   85.404699    3.779791  ...  26.8  28.6          44.7
32    16    5.666217    0.458949  ...  60.5  29.3          10.2
33    25   60.140261    4.969973  ...  30.3  28.0          41.7

[34 rows x 8 columns]